// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: trivy-java-db.proto

package serverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrivyJavaDB_SelectIndexByArtifactIDAndGroupID_FullMethodName    = "/trivyJavaDB.TrivyJavaDB/SelectIndexByArtifactIDAndGroupID"
	TrivyJavaDB_SelectIndexBySha1_FullMethodName                    = "/trivyJavaDB.TrivyJavaDB/SelectIndexBySha1"
	TrivyJavaDB_SelectIndexesByArtifactIDAndFileType_FullMethodName = "/trivyJavaDB.TrivyJavaDB/SelectIndexesByArtifactIDAndFileType"
)

// TrivyJavaDBClient is the client API for TrivyJavaDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrivyJavaDBClient interface {
	SelectIndexByArtifactIDAndGroupID(ctx context.Context, in *SelectIndexByArtifactIDAndGroupIDRequest, opts ...grpc.CallOption) (*SelectIndexByArtifactIDAndGroupIDResponse, error)
	SelectIndexBySha1(ctx context.Context, in *SelectIndexBySha1Request, opts ...grpc.CallOption) (*SelectIndexBySha1Response, error)
	SelectIndexesByArtifactIDAndFileType(ctx context.Context, in *SelectIndexesByArtifactIDAndFileTypeRequest, opts ...grpc.CallOption) (*SelectIndexesByArtifactIDAndFileTypeResponse, error)
}

type trivyJavaDBClient struct {
	cc grpc.ClientConnInterface
}

func NewTrivyJavaDBClient(cc grpc.ClientConnInterface) TrivyJavaDBClient {
	return &trivyJavaDBClient{cc}
}

func (c *trivyJavaDBClient) SelectIndexByArtifactIDAndGroupID(ctx context.Context, in *SelectIndexByArtifactIDAndGroupIDRequest, opts ...grpc.CallOption) (*SelectIndexByArtifactIDAndGroupIDResponse, error) {
	out := new(SelectIndexByArtifactIDAndGroupIDResponse)
	err := c.cc.Invoke(ctx, TrivyJavaDB_SelectIndexByArtifactIDAndGroupID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trivyJavaDBClient) SelectIndexBySha1(ctx context.Context, in *SelectIndexBySha1Request, opts ...grpc.CallOption) (*SelectIndexBySha1Response, error) {
	out := new(SelectIndexBySha1Response)
	err := c.cc.Invoke(ctx, TrivyJavaDB_SelectIndexBySha1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trivyJavaDBClient) SelectIndexesByArtifactIDAndFileType(ctx context.Context, in *SelectIndexesByArtifactIDAndFileTypeRequest, opts ...grpc.CallOption) (*SelectIndexesByArtifactIDAndFileTypeResponse, error) {
	out := new(SelectIndexesByArtifactIDAndFileTypeResponse)
	err := c.cc.Invoke(ctx, TrivyJavaDB_SelectIndexesByArtifactIDAndFileType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrivyJavaDBServer is the server API for TrivyJavaDB service.
// All implementations must embed UnimplementedTrivyJavaDBServer
// for forward compatibility
type TrivyJavaDBServer interface {
	SelectIndexByArtifactIDAndGroupID(context.Context, *SelectIndexByArtifactIDAndGroupIDRequest) (*SelectIndexByArtifactIDAndGroupIDResponse, error)
	SelectIndexBySha1(context.Context, *SelectIndexBySha1Request) (*SelectIndexBySha1Response, error)
	SelectIndexesByArtifactIDAndFileType(context.Context, *SelectIndexesByArtifactIDAndFileTypeRequest) (*SelectIndexesByArtifactIDAndFileTypeResponse, error)
	mustEmbedUnimplementedTrivyJavaDBServer()
}

// UnimplementedTrivyJavaDBServer must be embedded to have forward compatible implementations.
type UnimplementedTrivyJavaDBServer struct {
}

func (UnimplementedTrivyJavaDBServer) SelectIndexByArtifactIDAndGroupID(context.Context, *SelectIndexByArtifactIDAndGroupIDRequest) (*SelectIndexByArtifactIDAndGroupIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectIndexByArtifactIDAndGroupID not implemented")
}
func (UnimplementedTrivyJavaDBServer) SelectIndexBySha1(context.Context, *SelectIndexBySha1Request) (*SelectIndexBySha1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectIndexBySha1 not implemented")
}
func (UnimplementedTrivyJavaDBServer) SelectIndexesByArtifactIDAndFileType(context.Context, *SelectIndexesByArtifactIDAndFileTypeRequest) (*SelectIndexesByArtifactIDAndFileTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectIndexesByArtifactIDAndFileType not implemented")
}
func (UnimplementedTrivyJavaDBServer) mustEmbedUnimplementedTrivyJavaDBServer() {}

// UnsafeTrivyJavaDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrivyJavaDBServer will
// result in compilation errors.
type UnsafeTrivyJavaDBServer interface {
	mustEmbedUnimplementedTrivyJavaDBServer()
}

func RegisterTrivyJavaDBServer(s grpc.ServiceRegistrar, srv TrivyJavaDBServer) {
	s.RegisterService(&TrivyJavaDB_ServiceDesc, srv)
}

func _TrivyJavaDB_SelectIndexByArtifactIDAndGroupID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectIndexByArtifactIDAndGroupIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrivyJavaDBServer).SelectIndexByArtifactIDAndGroupID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrivyJavaDB_SelectIndexByArtifactIDAndGroupID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrivyJavaDBServer).SelectIndexByArtifactIDAndGroupID(ctx, req.(*SelectIndexByArtifactIDAndGroupIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrivyJavaDB_SelectIndexBySha1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectIndexBySha1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrivyJavaDBServer).SelectIndexBySha1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrivyJavaDB_SelectIndexBySha1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrivyJavaDBServer).SelectIndexBySha1(ctx, req.(*SelectIndexBySha1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrivyJavaDB_SelectIndexesByArtifactIDAndFileType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectIndexesByArtifactIDAndFileTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrivyJavaDBServer).SelectIndexesByArtifactIDAndFileType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrivyJavaDB_SelectIndexesByArtifactIDAndFileType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrivyJavaDBServer).SelectIndexesByArtifactIDAndFileType(ctx, req.(*SelectIndexesByArtifactIDAndFileTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrivyJavaDB_ServiceDesc is the grpc.ServiceDesc for TrivyJavaDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrivyJavaDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trivyJavaDB.TrivyJavaDB",
	HandlerType: (*TrivyJavaDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectIndexByArtifactIDAndGroupID",
			Handler:    _TrivyJavaDB_SelectIndexByArtifactIDAndGroupID_Handler,
		},
		{
			MethodName: "SelectIndexBySha1",
			Handler:    _TrivyJavaDB_SelectIndexBySha1_Handler,
		},
		{
			MethodName: "SelectIndexesByArtifactIDAndFileType",
			Handler:    _TrivyJavaDB_SelectIndexesByArtifactIDAndFileType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trivy-java-db.proto",
}
